set -e # Fail on error

echo building service-c started ...

sleep 0.3
echo building service-c 1/3 ...
sleep 0.3
echo building service-c 2/3 ...
sleep 0.3
echo building service-c 3/3 ...

echo building service-c ended !